server:  port: 9002  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fuelAppDb
      

  kafka:
    producer:
      bootstrap-servers: localhost:9092   
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer 
      
dispatch:
 topic:
   name: dispatch-topic   
   
auto:
  create:
    topics:
      enable: true
