

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fuelAppDb
      
 # cloud:
  #  stream:
     # bindings:
     #   output:
        #  destination: fueltopic
      #kafka:
       # binder:
        #  brokers: 127.0.0.1
         # defaultBrokerPort: 9092
  kafka:
    producer:
      bootstrap-servers: localhost:9092   
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer 
      
    consumer:
      group-id: dispatch
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
order:
 topic:
   name: order-topic
   
dispatch:
 topic:
   name: dispatch-topic
   

   
auto:
  create:
    topics:
      enable: true


   

          