spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fuelAppDb
      
 # cloud:
  #  stream:
     # bindings:
     #   output:
        #  destination: fueltopic
      #kafka:
       # binder:
        #  brokers: 127.0.0.1
         # defaultBrokerPort: 9092

         